---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible
  - sudo ansible-galaxy install jdauphant.nginx
  
  # Add ansible.cfg to pick up roles path.
  #- "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory localvm.yml --syntax-check
  
  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook -i tests/inventory localvm.yml --connection=local --sudo"
