---
- name: PHP | Add php-7.1 PPA
  apt_repository: repo='ppa:ondrej/php'
                  state=present
                  update_cache=yes
  sudo: true

- name: PHP | install php packages
  apt: pkg={{ item }} state=installed
  with_items:
    - php7.1-fpm
    - php7.1-cli
    - php7.1-common
    - php7.1-curl
    - php7.1-json
    - php7.1-gd
    - php7.1-mbstring
    - php7.1-mysql
    - php7.1-xmlrpc
    - php7.1-opcache
    - php7.1-intl
    - php7.1-bz2
    - php7.1-xml
    - php7.1-gmp
    - php7.1-zip
    - php-redis
  sudo: true
